Feature/start service
ufcg-lsd/arrebol pull request #22
Opened 2019-05-07 13:46 UTC by wesleymonte

2019-05-07 17:19 UTC, thiagomanel requested changes
changes are not mandatory, I'm satisfied with a reasonable answer to the point raised

2019-05-07 17:19 UTC, thiagomanel commented on bin/stop-service.sh
> +
is it the usual way to stop things in the context of springboot apps? I think lsof'ing things is not very reliable (at least, not much readable). Maybe, using pgrep or writing the pid of the process after calling the start script

2019-05-07 18:54 UTC, thiagomanel requested changes
almost done

2019-05-07 18:54 UTC, thiagomanel commented on bin/stop-service.sh
> +else
nice @wesleymonte. What if we do start-stop twice? the shutdown file keeps more than one pid?

2019-05-08 12:44 UTC, wesleymonte commented on bin/stop-service.sh
> +else
No @thiagomanel, when the service is stopped the shutdown.pid is automatically removed.

2019-05-08 12:45 UTC, thiagomanel commented on bin/stop-service.sh
> +else
cool, @wesleymonte. thanks

2019-05-08 12:45 UTC, thiagomanel approved these changes

2019-05-08 12:45 UTC, merged