[WIP] Docker task executor implementation to in worker namespace task script executor
ufcg-lsd/arrebol pull request #32
Opened 2019-06-17 19:40 UTC by paulofelipefeitosa

**TODO**: 

1. get exit codes from the _.ec_ file.
2. recovery logs output.

2019-06-18 14:38 UTC, thiagomanel requested changes
this review is also WIP. I'll fetch the code and (likely) send most issues latter

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/TaskExecutionResult.java
> +     * It returns the exit codes for the execution of the commands. When the @{link TaskExecutor}
update the javadoc. It returns the Commads not the exit codes

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/creator/DockerWorkerCreator.java
> +    private static final String TS_NAME = "in-namespace-task-script-executor.sh";
rename TS_NAME to TASK_SCRIPT_NAME there is no need to save chars here

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/creator/DockerWorkerCreator.java
> +    private static final String TS_NAME = "in-namespace-task-script-executor.sh";
run a code formatter in this class

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/docker/DockerTaskExecutor.java
> +    private static final String WORKER_TS_FILEPATH = "/tmp/task-script-executor.sh";
WORKER_TASK_SCRIPT_FILEPATH

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/docker/DockerTaskExecutor.java
> +    private static final String WORKER_TS_FILEPATH = "/tmp/task-script-executor.sh";
add file separators

2019-06-18 14:38 UTC, thiagomanel commented on src/main/resources/in-namespace-task-script-executor.sh
> +
we need some comments in this file. bash code is not straightforward

2019-06-18 14:38 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/arrebol/execution/docker/DockerTaskExecutor.java
> +        LOGGER.debug("Sending Task Script Executor to Docker Worker");
log the task id (and the container related info too)

2019-06-25 18:18 UTC, wesleymonte approved these changes

2019-06-25 18:23 UTC, wesleymonte approved these changes

2019-06-25 18:23 UTC, merged